server:
  port: 0
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
custom.property.value: 8
management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream
