spring.h2.console.enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    password: '{cipher}3a91f72b5362b946db8a64c312b39e954077558fa97eed73ec95b87cf9cfb91c8ce20f3cd4b80ebc552b9dfa5df661fa'  #tekstDoSzyfrowania
